---
##install optional packages
- name: install optional packages
  yum:
    name: "{{item}}" 
    state: present
  with_items:
    - net-tools
    - vim
    - bind-utils
    - zip
    - unzip
    - wget